volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: "pl"
    ports:
      - 8080:8080
